name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
projects: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. jane.doe@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen instead.
      placeholder: Type your description here...
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you experiencing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Other

  - type: textarea
    id: logs
    attributes:
      label: Relevant error messages
      description: Please copy and paste any relevant errors here.
      placeholder: |
        Traceback (most recent call last):
          File "<python-input-0>", line 1, in <module>
            raise RuntimeError("Something broke!")
        RuntimeError: Something broke!
      render: shell
